// src/components/Navigation.vue
<template>
  <div id="header" class='ui stackable menu'>
    <router-link to='/' class='item header'>keawade.io</router-link>
    <router-link to='/about' class='item' active-class='active'>about</router-link>
    <a class='item' href='http://github.com/keawade' target='_blank'><i class="fa fa-github fa-lg" aria-hidden="true"></i></a>
    <a class='item' href='http://twitter.com/TheKeithWade' target='_blank'><i class="fa fa-twitter fa-lg" aria-hidden="true"></i></a>
    <a class='item' href='http://linkedin.com/in/keawade' target='_blank'><i class="fa fa-linkedin fa-lg" aria-hidden="true"></i></a>
  </div>
</template>

<script>
import '../assets/menu.min.css'

export default {
  name: 'header'
}
</script>

<style lang='scss' scoped>
#header {
  margin-top: 0;
}
.ui.menu {
  .item {
    &.active {
      background-color: rgba(23,107,182, 0.05);
    }
    .item:hover {
      background-color: rgba(23,107,182, 0.03);
      &.active:hover {
        background-color: rgba(23,107,182, 0.03);
      }
    }
  }
}
</style>

// src/components/Navigation/Navigation.tsx
import * as React from 'react';
import { Link, RouteComponentProps } from 'react-router-dom';

import './Navigation.scss';

import {
  faGithub,
  faLinkedin,
  faMastodon,
  faTwitter,
} from '@fortawesome/free-brands-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { Image, Menu } from 'semantic-ui-react';

export const Navigation: React.FunctionComponent<
  RouteComponentProps
> = props => {
  return (
    <Menu id='navigation' stackable>
      <Menu.Item as={Link} to='/' header className='icon-heading'>
        <Image avatar className='keawade-avatar' src='/GithubAvatar.png' />
        <span>Keith Wade</span>
      </Menu.Item>
      <Menu.Item as={Link} to='/about' link>
        about
      </Menu.Item>
      <Menu.Item href='https://twitter.com/TheKeithWade' target='_blank'>
        <FontAwesomeIcon className='heading-icon' size='lg' icon={faTwitter} />
      </Menu.Item>
      <Menu.Item href='https://fosstodon.org/@keawade' target='_blank'>
        <FontAwesomeIcon className='heading-icon' size='lg' icon={faMastodon} />
      </Menu.Item>
      <Menu.Item href='https://github.com/keawade' target='_blank'>
        <FontAwesomeIcon className='heading-icon' size='lg' icon={faGithub} />
      </Menu.Item>
      <Menu.Item href='https://linkedin.com/in/keawade' target='_blank'>
        <FontAwesomeIcon className='heading-icon' size='lg' icon={faLinkedin} />
      </Menu.Item>
    </Menu>
  );
};
