// src/components/Home.vue
<template>
  <div id="home">
    <h1>Articles and Projects</h1>
    <div class='ui list'>
      <div v-for='post in posts' class='item'>
        <div class='content'>
          <router-link :to='post.filename' class='header' >{{post.title}}</router-link>
          <div class='description'>{{post.excerpt}}</div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { posts } from '../posts/posts.json'
import '../assets/list.min.css'

export default {
  name: 'home',
  data () {
    return {
      posts: posts.sort((a, b) => (Date.parse(a.date) < Date.parse(b.date)))
    }
  }
}
</script>

<style lang='scss' scoped>
</style>

// src/components/Home/Home.tsx
import * as React from 'react';
import { Link, RouteComponentProps } from 'react-router-dom';

import './Home.scss';

import moment from 'moment';
import { Header, List, Segment } from 'semantic-ui-react';

import { IPost, posts } from '../../posts/posts';

export const Home: React.FunctionComponent<RouteComponentProps> = props => {
  return (
    <Segment id='home'>
      <Header as='h1'>Articles and Projects</Header>
      <List className='article-list'>
        {posts
          .sort((a, b) => (new Date(a.date) < new Date(b.date) ? 1 : -1))
          .map(post => (
            <PostItem post={post} />
          ))}
      </List>
    </Segment>
  );
};

export const PostItem: React.FunctionComponent<{ post: IPost }> = ({
  post,
}) => {
  return (
    <List.Item className='article'>
      <div className='title'>
        <Header as='h2'>
          <Link to={`/posts/${post.filename}`}>{post.title}</Link>
        </Header>
        <div className='date'>{moment(post.date).format('LL')}</div>
      </div>
      <div className='excerpt'>{post.excerpt}</div>
    </List.Item>
  );
};
